

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApiGNB.InfrastructureAPI.EntityModel
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class GNBDataContext : DbContext
{
    public GNBDataContext()
        : base("name=GNBDataContext")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<M_Conversion> M_Conversion { get; set; }

    public virtual DbSet<M_Transactions> M_Transactions { get; set; }

    public virtual DbSet<T_ConvertedTransacctions> T_ConvertedTransacctions { get; set; }

}

}

