//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiGNB.InfrastructureAPI.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Transactions
    {
        public int Id { get; set; }
        public string TransactionSku { get; set; }
        public string Amount { get; set; }
        public string Currency { get; set; }
    }
}
