//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiGNB.InfrastructureAPI.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ConvertedTransacctions
    {
        public int Id { get; set; }
        public string sku_ { get; set; }
        public string amount_ { get; set; }
        public string amountCurrency__ { get; set; }
        public string change_ { get; set; }
        public string currency_ { get; set; }
    }
}
